name = input("Введите ваше имя >>>")
growth = int(input("Введите ваш рост >>>"))
weight = int(input("Введите ваш вес >>>"))
age = int(input("Введите ваш возраст >>>"))
sex = input("Введите ваш пол >>>")
print(f"Привет, {name}! Ваши данные следующие: ваш рост {growth}, ваш вес: {weight}, ваш возраст: {age}, ваш пол: {sex}")
